name: simasam
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  http: ^1.2.1
  pytorch_lite: ^4.2.5
  image_picker: ^1.0.8
  get_storage: any
  get: 4.6.6
  socket_io_client: ^2.0.3+1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/img/
    - assets/models/
    - assets/labels/
  uses-material-design: true

